---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-config
  namespace: plex
  labels:
    app.kubernetes.io/name: plex
data:
  # Configuration will be populated by ansible
  APP_URL: "https://plex.example.com"
