"""Convert K8s manifests to Jinja2 templates with BWS variable placeholders."""

import re
from typing import NamedTuple

import yaml


class TemplateVariable(NamedTuple):
    """A detected variable with its default value."""

    name: str
    default: str
    source: str  # which manifest field it came from


def detect_variables(doc: dict, app_name: str) -> list[TemplateVariable]:
    """Detect values in a K8s manifest that should become template variables."""
    variables: list[TemplateVariable] = []
    kind = doc.get("kind", "")

    # Replicas
    replicas = doc.get("spec", {}).get("replicas")
    if replicas is not None:
        variables.append(TemplateVariable("replicas", str(replicas), "spec.replicas"))

    # Container-level detection
    containers = (
        doc.get("spec", {})
        .get("template", {})
        .get("spec", {})
        .get("containers", [])
    )
    for container in containers:
        if image := container.get("image"):
            variables.append(TemplateVariable("image", image, "containers[].image"))
        for port in container.get("ports", []):
            if cp := port.get("containerPort"):
                variables.append(
                    TemplateVariable("container_port", str(cp), "containers[].ports[].containerPort")
                )
        resources = container.get("resources", {})
        limits = resources.get("limits", {})
        if cpu := limits.get("cpu"):
            variables.append(TemplateVariable("cpu_limit", cpu, "resources.limits.cpu"))
        if mem := limits.get("memory"):
            variables.append(
                TemplateVariable("memory_limit", mem, "resources.limits.memory")
            )

    # PVC storage size
    if kind == "PersistentVolumeClaim":
        storage = (
            doc.get("spec", {})
            .get("resources", {})
            .get("requests", {})
            .get("storage")
        )
        if storage:
            variables.append(TemplateVariable("storage_size", storage, "spec.resources.requests.storage"))

    return variables


def convert_to_j2_template(
    doc: dict, app_name: str, namespace: str
) -> str:
    """Convert a K8s manifest dict to a Jinja2 template string."""
    kind = doc.get("kind", "Unknown")

    # Render to YAML first
    text = yaml.dump(doc, default_flow_style=False, sort_keys=False)

    # Add J2 comment header
    header = (
        f"{{# Auto-generated by vm-builder scaffold for {app_name}.\n"
        f"   Follows golden-master prefix convention.\n"
        f"   Protected resources (prefix < 40): always kubectl apply.\n"
        f"   Workload resources (prefix >= 40): kubectl {{{{ kubectl_action }}}}. #}}\n"
    )

    # Replace namespace
    text = text.replace(f"namespace: {namespace}", "namespace: {{ app_namespace }}")

    # Replace app name in labels and metadata
    text = re.sub(
        rf'(app\.kubernetes\.io/name:\s*){re.escape(app_name)}',
        r'\1{{ app_name }}',
        text,
    )
    text = re.sub(
        rf'(name:\s*){re.escape(app_name)}(\s)',
        r'\1{{ app_name }}\2',
        text,
    )
    text = re.sub(
        rf'(app:\s*){re.escape(app_name)}(\s)',
        r'\1{{ app_name }}\2',
        text,
    )

    # Replace image
    containers = (
        doc.get("spec", {})
        .get("template", {})
        .get("spec", {})
        .get("containers", [])
    )
    for container in containers:
        if image := container.get("image"):
            text = text.replace(
                f"image: {image}",
                f"image: {{{{ image | default('{image}') }}}}",
            )

    return header + text
