---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-config
  namespace: elastic
  labels:
    app.kubernetes.io/name: elastic
data:
  # Configuration will be populated by ansible
  APP_URL: "https://elastic.example.com"
