---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elastic
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: observability
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: observability
  ports:
    - name: http
      port: 9200
      targetPort: http
      protocol: TCP
    - name: transport
      port: 9300
      targetPort: transport
      protocol: TCP
