---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elastic
  labels:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/component: observability
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kibana
    app.kubernetes.io/component: observability
  ports:
    - name: http
      port: 5601
      targetPort: http
      protocol: TCP
