---
apiVersion: v1
kind: Service
metadata:
  name: elastic
  namespace: elastic
  labels:
    app.kubernetes.io/name: elastic
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: elastic
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30920
