---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin

resources:
  - namespace.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: jellyfin
  app.kubernetes.io/part-of: golden-master
  app.kubernetes.io/managed-by: kustomize
