---
apiVersion: v1
kind: Service
metadata:
  name: teleport
  namespace: teleport
  labels:
    app.kubernetes.io/name: teleport
    app.kubernetes.io/component: zero-trust-access
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: teleport
    app.kubernetes.io/component: zero-trust-access
  ports:
    - name: ssh-proxy
      port: 3023
      targetPort: ssh-proxy
      protocol: TCP
    - name: tunnel
      port: 3024
      targetPort: tunnel
      protocol: TCP
    - name: auth
      port: 3025
      targetPort: auth
      protocol: TCP
    - name: kube
      port: 3027
      targetPort: kube
      protocol: TCP
    - name: web
      port: 3080
      targetPort: web
      protocol: TCP
