---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
  labels:
    app.kubernetes.io/name: qbittorrent
data:
  # Configuration will be populated by ansible
  APP_URL: "https://qbittorrent.example.com"
