---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kibana

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: kibana
  app.kubernetes.io/part-of: golden-master
  app.kubernetes.io/managed-by: kustomize
