"""Body schema FK field detection with recursive tree traversal.

Ported from RESTler ``Dependencies.fs:968-1010`` (visitLeaf, visitInner,
Tree.iterCtx).  Walks the entire body schema tree — every named property
at ANY depth becomes a candidate consumer.

The same-body filter (RESTler pattern) skips fields that also appear in
the response schema, since those are produced by this operation, not
consumed from another.
"""
from __future__ import annotations

from typing import Any

from idi.generation.dep_adapters.base import Dependency, DetectionSource, OperationInfo
from idi.generation.dep_adapters.naming import _engine, normalize, singularize
from idi.generation.dep_adapters.target_inference import (
    _CREDENTIAL_PARAMS,
    _has_fk_suffix,
    infer_target,
)

_EXCLUDED_FIELDS: frozenset[str] = frozenset({
    "namespace", "namespaces", "ns",
})

# Fields that are auto-generated by the server (not FK inputs).
# Only these should trigger the same-body filter.  Other response fields
# are just echoes of the request input and should NOT be filtered.
_SELF_PRODUCED_FIELDS: frozenset[str] = frozenset({
    "id", "pk", "uuid", "uid", "guid",
    "created", "created_at", "modified", "modified_at", "updated", "updated_at",
    "slug", "url", "self", "selflink",
})

_MAX_DEPTH = 8

# Identity fields that signal a nested object refers to an external resource.
_IDENTITY_FIELDS: frozenset[str] = frozenset({"id", "name", "uuid"})

# Depth threshold above which FK confidence is reduced.
_DEEP_NESTING_THRESHOLD = 3

# Confidence multiplier for FKs found at depth >= _DEEP_NESTING_THRESHOLD.
_DEEP_CONFIDENCE_FACTOR = 0.9375  # 0.8 * 0.9375 = 0.75


def _detect_nested_producer(
    container_name: str,
    inner_properties: dict[str, Any],
    known_resources: set[str],
    service: str,
) -> Dependency | None:
    """Resolve a nested object container name to a known resource FK.

    Returns a Dependency if the container name matches exactly one known resource
    and the inner object has an identity field (id, name, uuid). Returns None on
    ambiguity or no match.
    """
    # Check if inner properties include an identity field.
    if not _IDENTITY_FIELDS & set(inner_properties):
        return None

    # Generate normalized, singular, and plural forms of the container name.
    norm = normalize(container_name).replace("__", "")
    singular = singularize(norm)
    plural = _engine.plural_noun(norm)

    candidates = {norm, singular}
    if plural:
        candidates.add(plural)

    # Also try without common suffixes like "ref"
    for suffix in ("ref", "reference", "spec", "config"):
        for form in (norm, singular):
            if form.endswith(suffix) and len(form) > len(suffix):
                stripped = form[: -len(suffix)]
                candidates.add(stripped)
                p = _engine.plural_noun(stripped)
                if p:
                    candidates.add(p)

    # Match against known resources.
    matches: set[str] = set()
    for c in candidates:
        if c in known_resources:
            matches.add(c)

    # Ambiguity guard: only single-match resolution emits an edge.
    if len(matches) != 1:
        return None

    target = matches.pop()
    return Dependency(
        field=container_name,
        target_resource=target,
        target_operation="create",
        fact_ref=f"facts://{service}/{target}#id",
        confidence=0.8,
        source="generic_odg:body",
        lineage_type="copy",
        detection_source=DetectionSource.NESTED_PRODUCER,
    )


def detect_body_deps(
    operation: OperationInfo,
    known_resources: set[str],
) -> list[Dependency]:
    """Detect FK dependencies from the full body schema tree.

    Recursively walks nested objects and array items, extracting
    consumer candidates at every depth.
    """
    body = operation.body_schema
    if not body or "properties" not in body:
        return []

    # Build set of response field paths for same-body filtering.
    response_fields = _collect_response_fields(operation.response_schema)

    results: list[Dependency] = []
    _walk_body(
        schema=body,
        known_resources=known_resources,
        service=operation.service,
        resource=operation.resource,
        response_fields=response_fields,
        json_path=[],
        depth=0,
        results=results,
    )
    return results


def _walk_body(
    schema: dict[str, Any],
    known_resources: set[str],
    service: str,
    resource: str,
    response_fields: set[str],
    json_path: list[str],
    depth: int,
    results: list[Dependency],
    visited: set[int] | None = None,
) -> None:
    """Recursive body tree walker (RESTler Tree.iterCtx equivalent)."""
    if depth > _MAX_DEPTH or not isinstance(schema, dict):
        return

    # Circular reference detection via schema object identity.
    if visited is None:
        visited = set()
    schema_id = id(schema)
    if schema_id in visited:
        return
    visited = visited | {schema_id}  # Copy-on-add for branch isolation

    for field_name, field_info in schema.get("properties", {}).items():
        if not isinstance(field_info, dict):
            continue
        if field_name.lower() in _EXCLUDED_FIELDS:
            continue

        current_path = json_path + [field_name]
        container = json_path[-1] if json_path else None

        # Same-body filter: only skip fields that are auto-generated outputs
        # (pk, id, uuid, etc.) echoed in the response.  Most REST APIs echo
        # ALL input fields — only self-produced identifiers indicate this
        # operation is the true producer and should not be a consumer.
        path_key = "/".join(current_path)
        if path_key in response_fields and field_name.lower() in _SELF_PRODUCED_FIELDS:
            _recurse_nested(
                field_info, known_resources, service, resource,
                response_fields, current_path, depth, results, visited,
            )
            continue

        # Credential exclusion: skip credential-like fields at any depth.
        fn_lower = field_name.lower()
        if not _has_fk_suffix(fn_lower) and _CREDENTIAL_PARAMS.match(fn_lower):
            _recurse_nested(
                field_info, known_resources, service, resource,
                response_fields, current_path, depth, results, visited,
            )
            continue

        # Nested object producer: check if this field is an object whose
        # container name maps to a known resource.
        if field_info.get("type") == "object" and "properties" in field_info:
            nested_dep = _detect_nested_producer(
                container_name=field_name,
                inner_properties=field_info["properties"],
                known_resources=known_resources,
                service=service,
            )
            if nested_dep is not None:
                # Apply depth penalty to nested producer edges too.
                if depth >= _DEEP_NESTING_THRESHOLD:
                    nested_dep = Dependency(
                        **{**nested_dep.__dict__,
                           "confidence": round(nested_dep.confidence * _DEEP_CONFIDENCE_FACTOR, 3)},
                    )
                results.append(nested_dep)
                # Still recurse into the nested object for deeper FKs.
                _recurse_nested(
                    field_info, known_resources, service, resource,
                    response_fields, current_path, depth, results, visited,
                )
                continue

        # Try matching this field against known resources.
        target, confidence = infer_target(
            field_name, field_info, known_resources,
            container=container, json_path=current_path,
        )

        if target is not None:
            # Depth-based confidence adjustment.
            if depth >= _DEEP_NESTING_THRESHOLD:
                confidence *= _DEEP_CONFIDENCE_FACTOR
                confidence = round(confidence, 3)

            results.append(Dependency(
                field=field_name,
                target_resource=target,
                target_operation="create",
                fact_ref=f"facts://{service}/{target}#id",
                confidence=confidence,
                source="generic_odg:body",
                lineage_type="copy",
                detection_source=DetectionSource.NESTED_FK if depth > 0 else DetectionSource.DEFAULT,
            ))

        # Recurse into nested objects and arrays.
        _recurse_nested(
            field_info, known_resources, service, resource,
            response_fields, current_path, depth, results, visited,
        )


def _recurse_nested(
    field_info: dict[str, Any],
    known_resources: set[str],
    service: str,
    resource: str,
    response_fields: set[str],
    current_path: list[str],
    depth: int,
    results: list[Dependency],
    visited: set[int] | None = None,
) -> None:
    """Recurse into nested objects and array items."""
    # Nested object.
    if field_info.get("type") == "object" and "properties" in field_info:
        _walk_body(
            field_info, known_resources, service, resource,
            response_fields, current_path, depth + 1, results, visited,
        )

    # Array items with properties.
    items = field_info.get("items", {})
    if (
        field_info.get("type") == "array"
        and isinstance(items, dict)
        and "properties" in items
    ):
        _walk_body(
            items, known_resources, service, resource,
            response_fields, current_path + ["[0]"], depth + 1, results, visited,
        )

    # allOf composition — merge and recurse.
    if "allOf" in field_info:
        merged: dict[str, Any] = {"properties": {}}
        for sub in field_info["allOf"]:
            if isinstance(sub, dict) and "properties" in sub:
                merged["properties"].update(sub["properties"])
        if merged["properties"]:
            _walk_body(
                merged, known_resources, service, resource,
                response_fields, current_path, depth + 1, results, visited,
            )

    # oneOf / anyOf composition — merge and recurse (same as allOf).
    for key in ("oneOf", "anyOf"):
        if key in field_info:
            merged_variant: dict[str, Any] = {"properties": {}}
            for sub in field_info[key]:
                if isinstance(sub, dict) and "properties" in sub:
                    merged_variant["properties"].update(sub["properties"])
            if merged_variant["properties"]:
                _walk_body(
                    merged_variant, known_resources, service, resource,
                    response_fields, current_path, depth + 1, results, visited,
                )


def _collect_response_fields(
    response_schema: dict[str, Any] | None,
    prefix: str = "",
) -> set[str]:
    """Collect all field paths from the response schema for same-body filtering."""
    if not response_schema or not isinstance(response_schema, dict):
        return set()

    result: set[str] = set()
    for field_name in response_schema.get("properties", {}):
        path = f"{prefix}/{field_name}" if prefix else field_name
        result.add(path)
        # Recurse into nested response objects.
        sub = response_schema["properties"][field_name]
        if isinstance(sub, dict) and "properties" in sub:
            result.update(_collect_response_fields(sub, path))
    return result
