"""Body schema FK field detection with recursive tree traversal.

Ported from RESTler ``Dependencies.fs:968-1010`` (visitLeaf, visitInner,
Tree.iterCtx).  Walks the entire body schema tree — every named property
at ANY depth becomes a candidate consumer.

The same-body filter (RESTler pattern) skips fields that also appear in
the response schema, since those are produced by this operation, not
consumed from another.
"""
from __future__ import annotations

from typing import Any

from idi.generation.dep_adapters.base import Dependency, DetectionSource, OperationInfo
from idi.generation.dep_adapters.target_inference import infer_target

_EXCLUDED_FIELDS: frozenset[str] = frozenset({
    "namespace", "namespaces", "ns",
})

# Fields that are auto-generated by the server (not FK inputs).
# Only these should trigger the same-body filter.  Other response fields
# are just echoes of the request input and should NOT be filtered.
_SELF_PRODUCED_FIELDS: frozenset[str] = frozenset({
    "id", "pk", "uuid", "uid", "guid",
    "created", "created_at", "modified", "modified_at", "updated", "updated_at",
    "slug", "url", "self", "selflink",
})

_MAX_DEPTH = 8


def detect_body_deps(
    operation: OperationInfo,
    known_resources: set[str],
) -> list[Dependency]:
    """Detect FK dependencies from the full body schema tree.

    Recursively walks nested objects and array items, extracting
    consumer candidates at every depth.
    """
    body = operation.body_schema
    if not body or "properties" not in body:
        return []

    # Build set of response field paths for same-body filtering.
    response_fields = _collect_response_fields(operation.response_schema)

    results: list[Dependency] = []
    _walk_body(
        schema=body,
        known_resources=known_resources,
        service=operation.service,
        resource=operation.resource,
        response_fields=response_fields,
        json_path=[],
        depth=0,
        results=results,
    )
    return results


def _walk_body(
    schema: dict[str, Any],
    known_resources: set[str],
    service: str,
    resource: str,
    response_fields: set[str],
    json_path: list[str],
    depth: int,
    results: list[Dependency],
) -> None:
    """Recursive body tree walker (RESTler Tree.iterCtx equivalent)."""
    if depth > _MAX_DEPTH or not isinstance(schema, dict):
        return

    for field_name, field_info in schema.get("properties", {}).items():
        if not isinstance(field_info, dict):
            continue
        if field_name.lower() in _EXCLUDED_FIELDS:
            continue

        current_path = json_path + [field_name]
        container = json_path[-1] if json_path else None

        # Same-body filter: only skip fields that are auto-generated outputs
        # (pk, id, uuid, etc.) echoed in the response.  Most REST APIs echo
        # ALL input fields — only self-produced identifiers indicate this
        # operation is the true producer and should not be a consumer.
        path_key = "/".join(current_path)
        if path_key in response_fields and field_name.lower() in _SELF_PRODUCED_FIELDS:
            _recurse_nested(
                field_info, known_resources, service, resource,
                response_fields, current_path, depth, results,
            )
            continue

        # Try matching this field against known resources.
        target, confidence = infer_target(
            field_name, field_info, known_resources,
            container=container, json_path=current_path,
        )

        if target is not None:
            results.append(Dependency(
                field=field_name,
                target_resource=target,
                target_operation="create",
                fact_ref=f"facts://{service}/{target}#id",
                confidence=confidence,
                source="generic_odg:body",
                lineage_type="copy",
                detection_source=DetectionSource.DEFAULT,
            ))

        # Recurse into nested objects and arrays.
        _recurse_nested(
            field_info, known_resources, service, resource,
            response_fields, current_path, depth, results,
        )


def _recurse_nested(
    field_info: dict[str, Any],
    known_resources: set[str],
    service: str,
    resource: str,
    response_fields: set[str],
    current_path: list[str],
    depth: int,
    results: list[Dependency],
) -> None:
    """Recurse into nested objects and array items."""
    # Nested object.
    if field_info.get("type") == "object" and "properties" in field_info:
        _walk_body(
            field_info, known_resources, service, resource,
            response_fields, current_path, depth + 1, results,
        )

    # Array items with properties.
    items = field_info.get("items", {})
    if (
        field_info.get("type") == "array"
        and isinstance(items, dict)
        and "properties" in items
    ):
        _walk_body(
            items, known_resources, service, resource,
            response_fields, current_path + ["[0]"], depth + 1, results,
        )

    # allOf composition — merge and recurse.
    if "allOf" in field_info:
        merged: dict[str, Any] = {"properties": {}}
        for sub in field_info["allOf"]:
            if isinstance(sub, dict) and "properties" in sub:
                merged["properties"].update(sub["properties"])
        if merged["properties"]:
            _walk_body(
                merged, known_resources, service, resource,
                response_fields, current_path, depth + 1, results,
            )

    # oneOf / anyOf composition — merge and recurse (same as allOf).
    for key in ("oneOf", "anyOf"):
        if key in field_info:
            merged_variant: dict[str, Any] = {"properties": {}}
            for sub in field_info[key]:
                if isinstance(sub, dict) and "properties" in sub:
                    merged_variant["properties"].update(sub["properties"])
            if merged_variant["properties"]:
                _walk_body(
                    merged_variant, known_resources, service, resource,
                    response_fields, current_path, depth + 1, results,
                )


def _collect_response_fields(
    response_schema: dict[str, Any] | None,
    prefix: str = "",
) -> set[str]:
    """Collect all field paths from the response schema for same-body filtering."""
    if not response_schema or not isinstance(response_schema, dict):
        return set()

    result: set[str] = set()
    for field_name in response_schema.get("properties", {}):
        path = f"{prefix}/{field_name}" if prefix else field_name
        result.add(path)
        # Recurse into nested response objects.
        sub = response_schema["properties"][field_name]
        if isinstance(sub, dict) and "properties" in sub:
            result.update(_collect_response_fields(sub, path))
    return result
