apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: neo4j

resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
  - configmap-schemas.yaml

commonLabels:
  app.kubernetes.io/name: neo4j
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: graphrag
  app.kubernetes.io/managed-by: kustomize
