---
apiVersion: v1
kind: Service
metadata:
  name: longhorn
  namespace: longhorn
  labels:
    app.kubernetes.io/name: longhorn
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: longhorn
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30800
