---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: alertmanager
  ports:
    - port: 9093
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30903
