---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: server
spec:
  serviceName: alertmanager
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.27.0
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 9093
              name: http
          envFrom:
            - configMapRef:
                name: alertmanager-config
            - secretRef:
                name: alertmanager-secrets
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 10Gi
