---
- name: Uninstall Longhorn Storage
  hosts: "{{ target_hosts | default('localhost') }}"
  gather_facts: false
  become: false

  vars:
    app_name: longhorn
    app_namespace: "longhorn-system"
  tasks:
    - name: Check namespace exists
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: "{{ app_namespace }}"
      register: ns_check

    - name: Skip if namespace does not exist
      ansible.builtin.meta: end_play
      when: ns_check.resources | length == 0

    - name: Delete Longhorn StorageClass
      kubernetes.core.k8s:
        api_version: storage.k8s.io/v1
        kind: StorageClass
        name: longhorn
        state: absent
      failed_when: false

    - name: Delete all Longhorn Deployments
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: "{{ app_namespace }}"
      register: longhorn_deployments

    - name: Remove Longhorn Deployments
      kubernetes.core.k8s:
        api_version: apps/v1
        kind: Deployment
        name: "{{ item.metadata.name }}"
        namespace: "{{ app_namespace }}"
        state: absent
        wait: true
        wait_timeout: 120
      loop: "{{ longhorn_deployments.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"

    - name: Delete all Longhorn DaemonSets
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: DaemonSet
        namespace: "{{ app_namespace }}"
      register: longhorn_daemonsets

    - name: Remove Longhorn DaemonSets
      kubernetes.core.k8s:
        api_version: apps/v1
        kind: DaemonSet
        name: "{{ item.metadata.name }}"
        namespace: "{{ app_namespace }}"
        state: absent
        wait: true
        wait_timeout: 120
      loop: "{{ longhorn_daemonsets.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"

    - name: Delete all Services in longhorn-system
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        namespace: "{{ app_namespace }}"
      register: longhorn_services

    - name: Remove Longhorn Services
      kubernetes.core.k8s:
        api_version: v1
        kind: Service
        name: "{{ item.metadata.name }}"
        namespace: "{{ app_namespace }}"
        state: absent
      loop: "{{ longhorn_services.resources }}"
      loop_control:
        label: "{{ item.metadata.name }}"
