#!/bin/bash
# GCP Startup Script for K3s VM Bootstrap
# Generated by Terraform for VM: ${vm_name}
# Minimal bootstrap: Install runner + basics, let playbooks handle the rest

set -euo pipefail

# Logging
exec > >(tee /var/log/startup-script.log)
exec 2>&1

echo "=== Starting GCP startup script for ${vm_name} ==="
date

# Set hostname
hostnamectl set-hostname ${vm_name}
echo "127.0.0.1 ${vm_name}" >> /etc/hosts

# Update package list
export DEBIAN_FRONTEND=noninteractive
apt-get update

# Install base packages
apt-get install -y \
  curl \
  gnupg \
  jq \
  unzip \
  python3 \
  python3-pip \
  ansible \
  git

# Create ubuntu user if doesn't exist (GCP uses your email by default)
if ! id -u ubuntu >/dev/null 2>&1; then
  useradd -m -s /bin/bash -G sudo ubuntu
  echo "ubuntu ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ubuntu
  chmod 0440 /etc/sudoers.d/ubuntu
fi

# Add SSH keys to ubuntu user
mkdir -p /home/ubuntu/.ssh
chmod 700 /home/ubuntu/.ssh
%{ for key in ssh_authorized_keys ~}
echo "${key}" >> /home/ubuntu/.ssh/authorized_keys
%{ endfor ~}
chmod 600 /home/ubuntu/.ssh/authorized_keys
chown -R ubuntu:ubuntu /home/ubuntu/.ssh

# GitHub Actions Runner Installation
echo "=== Installing GitHub Actions runner ==="

# Create runner user
useradd -m -s /bin/bash runner || true
usermod -aG sudo runner || true
echo "runner ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/runner
chmod 0440 /etc/sudoers.d/runner

cd /home/runner || exit 0

# Resolve latest runner version from GitHub API
RUNNER_VERSION=$(curl -s https://api.github.com/repos/actions/runner/releases/latest | grep '"tag_name"' | sed 's/.*"v\(.*\)".*/\1/')
if [ -z "$RUNNER_VERSION" ]; then
  RUNNER_VERSION="${github_runner_version}"
  echo "WARNING: Could not fetch latest runner version, falling back to $RUNNER_VERSION"
fi
echo "Using GitHub Actions runner version: $RUNNER_VERSION"
curl -o actions-runner.tar.gz -L \
  "https://github.com/actions/runner/releases/download/v$${RUNNER_VERSION}/actions-runner-linux-x64-$${RUNNER_VERSION}.tar.gz" || exit 0

tar xzf actions-runner.tar.gz || exit 0
chown -R runner:runner /home/runner || true

mkdir -p /home/runner/.ssh && chmod 700 /home/runner/.ssh

# SSH deploy key (base64-encoded private key)
PRIVATE_KEY_B64='${ssh_private_key_b64}'
RUNNER_TOKEN='${runner_token}'

if [ -n "$PRIVATE_KEY_B64" ]; then
  echo "$PRIVATE_KEY_B64" | base64 -d > /home/runner/.ssh/id_ed25519 || true
  chmod 600 /home/runner/.ssh/id_ed25519 || true
  ssh-keyscan github.com >> /home/runner/.ssh/known_hosts 2>/dev/null || true
  chmod 644 /home/runner/.ssh/known_hosts || true
  chown -R runner:runner /home/runner/.ssh || true
  echo "SSH deploy key configured"
fi

# Register runner if token was provided
# Label with VM hostname for unique targeting
if [ -n "$RUNNER_TOKEN" ]; then
  echo "Registering GitHub Actions runner..."
  sudo -u runner ./config.sh \
    --url "https://github.com/${github_repo}" \
    --token "$RUNNER_TOKEN" \
    --name '${vm_name}' \
    --labels "self-hosted,gcp,${vm_name}" \
    --unattended \
    --disableupdate || exit 0

  echo "Installing runner service..."
  ./svc.sh install runner || true
  ./svc.sh start || true
  echo "GitHub Actions runner started"
else
  echo "No runner token provided, skipping runner registration"
fi

# Install Tailscale (for networking)
echo "=== Installing Tailscale ==="
curl -fsSL https://tailscale.com/install.sh | sh

echo "=== Startup script complete for ${vm_name} ==="
date
echo "VM is ready for Phase 2.5 bootstrap"
