---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-secrets
  namespace: media-stack
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: qbittorrent-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/apps/media-stack/qbittorrent
        property: username
    - secretKey: password
      remoteRef:
        key: secret/apps/media-stack/qbittorrent
        property: password
    - secretKey: url
      remoteRef:
        key: secret/apps/media-stack/qbittorrent
        property: url
    - secretKey: nodeport_url
      remoteRef:
        key: secret/apps/media-stack/qbittorrent
        property: nodeport_url
