---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-stack

resources:
  - namespace.yaml
  - services.yaml
  - sonarr-statefulset.yaml
  - radarr-statefulset.yaml
  - sabnzbd-statefulset.yaml
  - prowlarr-statefulset.yaml
  - qbittorrent-statefulset.yaml

commonLabels:
  app.kubernetes.io/part-of: media-stack
  app.kubernetes.io/managed-by: kustomize
