---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-stack

resources:
  - prowlarr-ingressroute.yaml
  - sonarr-ingressroute.yaml
  - radarr-ingressroute.yaml
  - sabnzbd-ingressroute.yaml
  - qbittorrent-ingressroute.yaml

commonLabels:
  app.kubernetes.io/part-of: media-stack
  managed-by: kustomize
