---
- name: "Create Kind cluster"
  ansible.builtin.import_playbook: ../shared/create-kind.yml

- name: "Prepare namespaces"
  ansible.builtin.import_playbook: ../shared/prepare-namespaces.yml

- name: "Ensure prometheus namespace"
  hosts: localhost
  gather_facts: false
  environment:
    KUBECONFIG: /tmp/molecule-kubeconfig
  tasks:
    - name: Create prometheus namespace
      ansible.builtin.shell: >-
        kubectl create namespace observability --dry-run=client -o yaml | kubectl apply -f -
      changed_when: false

- name: "Deploy prometheus"
  ansible.builtin.import_playbook: ../../../apps/prometheus/install/01-deploy.yml
